# Generated by Django 2.2 on 2021-02-07 10:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0021_article_comment_approved_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='author_name',
        ),
        migrations.AddField(
            model_name='articles',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article_comment',
            name='comment_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='articles',
            name='article',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='articles',
            name='post_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
